// Plan review: checklists, parsers and the full text-layer pipeline on the
// synthetic drawing sets (tests/drawings, generated by scripts/make-test-drawings.py).
import assert from "node:assert/strict";
import fs from "node:fs";
import { test } from "node:test";
import { loadNational } from "../lib/corpus.ts";
import { ALL_CHECKS } from "../lib/review/checklists/index.ts";
import { runCompliance, runDraft, runManifest, runSheetReview } from "../lib/review/flows/plan-review.ts";
import { koNumber, landscapeTiers, zoneLimit } from "../lib/review/skills/parse.ts";
import type { PageInput } from "../lib/review/types.ts";
import { layoutText, undouble } from "../lib/review/utils/layout.ts";
import { normalizeLine, readSheetIdentity } from "../lib/review/utils/read-text.ts";
import { finalItems, mergeValues, plannedGroups, verifyArtifacts } from "../lib/review/utils/session.ts";

process.env.GEMINI_API_KEY = ""; // text layer only — deterministic

const load = (name: string) => JSON.parse(fs.readFileSync(`tests/drawings/${name}.pages.json`, "utf8")).pages as PageInput[];
const truth = (name: string) => JSON.parse(fs.readFileSync(`tests/drawings/${name}.truth.json`, "utf8")).facts as Record<string, number | string>;

async function review(name: string) {
  const pages = load(name);
  const manifest = await runManifest(pages);
  const files = [];
  for (const g of plannedGroups(manifest, "full")) files.push(await runSheetReview({ group: g.group.key, pages: g.sheets.map(s => pages.find(p => p.page === s.page)!), manifest }));
  const values = mergeValues(files);
  const findings = files.flatMap(f => f.findings);
  const state = await runCompliance({ scope: "state", values, findings, region: manifest.project.region });
  const city = await runCompliance({ scope: "city", values, findings, region: manifest.project.region, state });
  const out = runDraft({ manifest, findings: files, state, city });
  const status = Object.fromEntries(finalItems(state, city).map(i => [i.check_id, i.status]));
  return { manifest, values, state, city, status, ...out };
}

test("every checklist code basis exists in the corpus", () => {
  const n = loadNational();
  for (const c of ALL_CHECKS) for (const id of c.code_basis) assert.ok(n.byId.has(id), `${c.id}: ${id}`);
});

test("parsers: Korean numbers, zone tables, landscape tiers", () => {
  assert.equal(koNumber("1천500"), 1500);
  assert.equal(koNumber("2천"), 2000);
  assert.equal(koNumber("1,100"), 1100);
  const far = loadNational().byId.get("국토의계획및이용에관한법률시행령#85")!;
  assert.equal(zoneLimit(far.text, "제2종일반주거지역")?.value, 250);
  assert.equal(zoneLimit("4. 제2종 일반주거지역 : 240퍼센트 이하. 다만, 정비사업은 250퍼센트 이하로 한다.", "제2종일반주거지역")?.value, 240);
  const tiers = landscapeTiers("1. 연면적 2천 제곱미터 이상인 건축물 : 대지면적의 15퍼센트 이상\n2. 연면적 1천 제곱미터 이상 2천 제곱미터 미만인 건축물 : 대지면적의 10퍼센트 이상\n3. 연면적 1천 제곱미터 미만인 건축물 : 대지면적의 5퍼센트 이상");
  assert.deepEqual(tiers.map(t => [t.minGfa, t.maxGfa, t.percent]), [[2000, Infinity, 15], [1000, 2000, 10], [0, 1000, 5]]);
});

test("layout: line grouping, doubled CAD glyphs, letter-spaced titles", () => {
  const t = layoutText([{ str: "대지면적", x: 10, y: 100, w: 40, h: 10 }, { str: "330.00 ㎡", x: 120, y: 100.5, w: 40, h: 10 }, { str: "대지면적", x: 10.3, y: 100.2, w: 40, h: 10 }], 200);
  assert.equal(t, "대지면적 | 330.00 ㎡");
  assert.equal(undouble("대지위치대지위치 a\n위치도위치도\n설계개요설계개요"), "대지위치 a\n위치도\n설계개요");
  assert.equal(normalizeLine("건 폐 율 | % | 13.01"), "건폐율 | % | 13.01");
  assert.deepEqual(readSheetIdentity("도 면 명 | 배치도\n도면번호 | A-101"), { sheet_id: "A-101", title: "배치도" });
});

test("case A (compliant): values match ground truth and nothing fails", async () => {
  const r = await review("case-a-compliant");
  const t = truth("case-a-compliant");
  for (const k of ["대지면적", "건축면적", "연면적", "용적률산정용연면적", "높이", "주차대수", "조경면적", "접도길이", "정북이격_10m초과"]) assert.equal(r.values[k as keyof typeof r.values]?.value, t[k], k);
  assert.equal(r.manifest.project.region, "경기도/용인시");
  assert.ok(!Object.values(r.status).includes("FAIL"), JSON.stringify(r.status));
  assert.equal(r.status["2A"], "PASS");
  assert.equal(r.status["3B"], "PASS");
  assert.equal(r.status["4A"], "PASS");
  assert.ok(verifyArtifacts({ "sheet-manifest.json": r.manifest, "sheet_findings.json": [], "state_compliance.json": r.state, "city_compliance.json": r.city, "draft_corrections.json": r.draft, "draft_corrections.md": r.md, "review_summary.json": r.summary }).allPresent);
});

test("case B (violations): each planted violation is a cited correction", async () => {
  const r = await review("case-b-violations");
  for (const id of ["2A", "2B", "3A", "3B", "4A"]) assert.equal(r.status[id], "FAIL", id);
  assert.equal(r.status["3C"], "UNCLEAR"); // 3대 < 5대 but the 조례 별표 is not in the corpus → reviewer VERIFY, not a hard FAIL
  const byId = Object.fromEntries(r.draft.items.map(i => [i.check_id, i]));
  assert.match(byId["2A"].code_citation.join(" "), /용인시 도시계획 조례/);
  assert.match(byId["3B"].description, /16\.5㎡/);
  assert.match(byId["4A"].description, /7\.1m/);
  assert.equal(byId["3C"].reviewer_action, "VERIFY");
  // Ordinance quotes are verbatim from the article text.
  const city2A = r.city.items.find(i => i.check_id === "2A")!;
  assert.ok(city2A.citations.every(c => c.verified), JSON.stringify(city2A.citations));
});
